// src/components/MoodSliderCategory.svelte
<script>
  import { createEventDispatcher } from "svelte";
  const dispatch = createEventDispatcher();

  import MoodSlider from "./MoodSlider.svelte";

  export let categoryName;
  export let sliders;

  function signalRecompute(e) {
    dispatch("signalRecomputeRecommendations", {
      ...e.detail,
      categoryName,
    });
  }
</script>

<h2>{categoryName.charAt(0).toUpperCase() + categoryName.slice(1)}</h2>
{#each sliders as slider}
  <MoodSlider {slider} on:signalRecomputeRecommendations={signalRecompute} />
{/each}

// src/components/MoodSliderCategory.vue
<template>
  <div>
    <h2>{{ categoryName.charAt(0).toUpperCase() + categoryName.slice(1) }}</h2>
    <div div :key="slider.name" v-for="slider in sliders">
      <MoodSlider :slider="slider" @signal-recompute-recommendations="signalRecompute" />
    </div>
  </div>
</template>

<script>
import MoodSlider from "./MoodSlider.vue";
export default {
  name: "MoodSliderCategory",
  components: {
    MoodSlider
  },
  props: {
    categoryName: String,
    sliders: Array
  },
  methods: {
    signalRecompute(sliderName, sliderValue, ignore) {
      this.$emit(
        "signal-recompute-recommendations",
        this.categoryName,
        sliderName,
        sliderValue,
        ignore
      );
    }
  }
};
</script>

<style scoped>
</style>
